#cloud-config
#create files
write_files:
  - path: /etc/motd # ASCII art displayed when someone logs in on terminal
    content: |1
        This is the SDI4Apps platform
        ____  ____ ___ _  _     _
       / ___||  _ \_ _| || |   / \   _ __  _ __  ___
       \___ \| | | | || || |_ / _ \ |  _ \|  _ \/ __|
        ___) | |_| | ||__   _/ ___ \| |_) | |_) \__ \
       |____/|____/___|  |_|/_/   \_\  __/|  __/|___/
                                    |_|   |_|

       SDI4Apps platform installation is in progress now. Please wait.
       It takes approximately 10 minutes. You can watch the progress
       by issuing the following command:

       tail -f /var/log/cloud-init-output.log

       and wait for the following line to appear: "The SDI4Apps platform installation was completed"
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |1
     Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
        "${distro_id}:${distro_codename}-updates";
     };
     Unattended-Upgrade::Mail "root";
     Unattended-Upgrade::MailOnlyOnError "true";
     Unattended-Upgrade::Remove-Unused-Dependencies "true";
     Unattended-Upgrade::Automatic-Reboot "true";
     Unattended-Upgrade::Automatic-Reboot-Time "02:00";

#add software repositories 
apt_sources:
  - source: "ppa:webupd8team/java"    # Oracle Java PPA (add-apt-repository ppa:webupd8team/java)
  - source: "ppa:ubuntugis/ubuntugis-unstable" # UbuntuGIS PPA
  - source: 'deb http://packages.comsode.eu/debian jessie main' # Open Data Node repository
    filename: odn.list
    key: |
      ----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v1.4.12 (GNU/Linux)
      
      mQENBFSzhn0BCACz6AzI4L4wSerczlwq4lX4cq6BFEKxH8wPiQRx0jH7mbk6rM1v
      HnV5/iLS78jcYuXFZ2vs1GMueioOI+52WhOlZ1nqmXtm9ID43uZUUeeCHUBGgy33
      yrluPqvG5x9pEsaM5ziJNJVjIdodYnMBSPgTPYNsF/9skkpRc18hVchKWaVtYVNT
      gvMAJMGTjyZ9ha9A+Qd3TU2E7qg/KTqQH0L3oQXKyAekxhZJ4JVmZ7N/1TA95dtr
      ZNXiTu1CF0Z9yrlNhvY8YXh8Xe7oxeFki6MO7qbgkj+mwbUKiomlGXRHzOtgDEzO
      f3uxnePB+T6QTD22fj6swI6NUg4wwjYqTvAxABEBAAG0HkphbiBNYXJjZWsgPGph
      bi5tYXJjZWtAZWVhLnNrPokBPgQTAQIAKAUCVLOGfQIbAwUJA8JnAAYLCQgHAwIG
      FQgCCQoLBBYCAwECHgECF4AACgkQLQOMPLy92WsJcwf8DTdtDRctp7wbV83bstWs
      zQjBNyh+mXJE3qqcRziGC92f69MxtpeuOn40E5i3ui1rsiuCYHjkKLdJZLc6NWPW
      pCVJkM0Ia6NDHNVn6quMX76LbKiyHiKfnF+4d83tvuD+Bc+Af83uqMWW4XwhgSNx
      Wr+VEvWWxWNcGE0GvpskWeKIlHdIUDAQywMaYInXLAi9CeyH2QjGNXX/01duaubb
      lJ6Jf77i9lkF4cb66mRTpiEw1NYTRPKPpezaTV/ZP7HUH5gVruMs/elCORV1NQcB
      Ar/ZVIjf8FXqACZIvVMBjlMjgJeu0KzSARmiyl2QAcECB4nd5qvsAWlWGZDSmyra
      krkBDQRUs4Z9AQgAw/q6T4JkutqE3KfHRgjN6Qst8Lr8VoXMP3B/5p3+Jfi0Pk9e
      G96oMvdSNPkR+1Cm2nRqRPyWP9ofZ4wsKcLyEUOsz/lqnX02d8XBXvI86ePnP5FG
      ZCNvWBlMdvzZLVJjhS1kPVJ9OQwfG+5vhzdE8vFooWLClsOvzh16f3lxEeRjHS+V
      Xeeko9c/NNPXOjqBreP6smFakk3i/lZZCqg842QKampeCrEnf8rgT1VlCRBbsOzx
      pb6RWqPrd9JpmjwaHHIvFkITD6JaximBIvvyU3AN+irUdZ40Cuvh7CGJwXusqfmQ
      7qAWC4T3pjvM0zj+nQ93veZf3SuURLjOT5xmWQARAQABiQElBBgBAgAPBQJUs4Z9
      AhsMBQkDwmcAAAoJEC0DjDy8vdlrKl4H/iTeyNnWgYMrDsisrjEPvSWoSfa41HEJ
      deYZ2x7rFxIvAoAxBQiv0fhS+U3A+SCS65hwh8Dj4BuT3rqpwNpbxsnguJtck2YX
      nOlCmBei4LSswjXqzPKmwygN+kotwRjaYQihpTlX+lBZprKrvoYoMqdhfkKth9+T
      qd+NVj/nzoyFEpGL9GVl6DeA63izrPlyns2TEFm3eOkRyj7JRkzJ+5T50imU3URB
      y49KzXIJlVb1SSVppO5mY0bzY8VH7b6R9C4UOvc7wO+IEDZdum8uvuTk2oD2VKNo
      cPUyF1ErD0FmRCiCq7OzdX+VYwKzg7UdPSmO55BSmot/rHbrsCKp9Tk=
      =AxsG
      -----END PGP PUBLIC KEY BLOCK-----
#update packages to latest versions
apt_update: True
#apt_upgrade: True
# Agreement with Oracle licence before packages are installed
# setting up Postfix SMTP server for outgoing email
bootcmd:
  - 'echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections'
  - 'echo postfix postfix/main_mailer_type select Internet Site | /usr/bin/debconf-set-selections'
  - 'echo postfix postfix/mailname string  $(hostname -f) | /usr/bin/debconf-set-selections'
#install these packages
packages:
  - ant
  - cgi-mapserver 
  - fail2ban
  - gdal-bin 
  - htop
  - libapache2-mod-php7.0
  - libapache2-mod-python 
  - mailutils
  - nodejs 
  - npm 
  - ntp
  - oracle-java7-installer
  - oracle-java7-unlimited-jce-policy
  - oracle-java7-set-default
  - php7.0
  - php7.0-curl 
  - php7.0-mysql 
  - php7.0-pgsql 
  - php7.0-sqlite 
  - php7.0-xsl
  - phppgadmin
  - postgis
  - postfix
  - postgresql-9.5-pgrouting
  - python-cssutils 
  - python-gdal 
  - python-html5lib 
  - python-httplib2 
  - python-lxml 
  - python-psycopg2 
  - python-pycurl 
  - python-pyproj 
  - python-webpy 
  - subversion 
  - sqlite3 
  - virtuoso-opensource
#  - unixodbc #Virtuoso dependencies
#  - mono-reference-assemblies-2.0
#create some users
users:
  #creates default user named "ubuntu" (as specified in /etc/cloud/cloud.cfg)
  - default
  #add another user
  - name: makub
    gecos: Martin Kuba
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtv24kBxvFCiDAUxQvsYEaIoWdU+QVgcWU1q4uJ8Ngy+LKn6XIVQTKlWd9W7MPUgpL5jPHVgExN1vpH+UlS0cducDUCRVB3JU4fW8jXge/JEhqhfrwKMD/iE0DJ0k2Zxd8pyIway1Q2KYs5tqQTJcQX3FsJ2V86pDFeLYmisRTFbo4n0wog20euPYCuTAY0KlA8mkOb/WXUcLICgT3O6Tvp9Vyez1P1eHT1DW7dkeu5hqal08raXNGwF9+xvo2oHzstTSHl/juXS+gmiI1Y4VqRiR0C6Euy/MBX4ywyOi/Fm8r9qxcvYaULsy/k8KudNjipL5KQxd/xKpw2Azs7fbbw== makub@acrab.ics.muni.cz
#aad the following ssh keys to the first specified user
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtv24kBxvFCiDAUxQvsYEaIoWdU+QVgcWU1q4uJ8Ngy+LKn6XIVQTKlWd9W7MPUgpL5jPHVgExN1vpH+UlS0cducDUCRVB3JU4fW8jXge/JEhqhfrwKMD/iE0DJ0k2Zxd8pyIway1Q2KYs5tqQTJcQX3FsJ2V86pDFeLYmisRTFbo4n0wog20euPYCuTAY0KlA8mkOb/WXUcLICgT3O6Tvp9Vyez1P1eHT1DW7dkeu5hqal08raXNGwF9+xvo2oHzstTSHl/juXS+gmiI1Y4VqRiR0C6Euy/MBX4ywyOi/Fm8r9qxcvYaULsy/k8KudNjipL5KQxd/xKpw2Azs7fbbw== makub@acrab.ics.muni.cz
# run script that installs SDI4Apps software
runcmd:
 - 'wget --quiet https://raw.githubusercontent.com/SDI4Apps/cloud-platform/master/install_sdi4apps_xenial.sh -O /tmp/install_sdi4apps.sh'
 - 'bash /tmp/install_sdi4apps.sh'
#final message
final_message: "The SDI4Apps platform installation was completed after $UPTIME seconds"
